package org.example.logic.utils

class BlankInputException(message: String) : Exception(message)
class UserNotFoundException(message: String) : Exception(message)
class NoLoggedInUserException(message: String) : Exception(message)
class UserAlreadyExistsException(message: String) : Exception(message)
class ProjectNotChangedException(message: String) : Exception(message)
class ProjectNotFoundException(message: String) : Exception(message)
class ProjectCreationFailedException(message: String) : Exception(message)
class TaskNotChangedException(message: String) : Exception(message)
class TaskNotFoundException(message: String) : Exception(message)
class StateNotFoundException(message: String) : Exception(message)
class InvalidInputException(message: String) : Exception(message)
class UnauthorizedException(message: String) : Exception(message)
class AuditInputException(message: String) : Exception(message)
class NoProjectsFoundException(message: String) : Exception(message)
class InvalidUserNameInputException(message: String) : Exception(message)
class AuditLogNotFoundException(message: String) : Exception(message)
class AuditLogCreationFailedException(message: String) : Exception(message)
class TaskNotCreatedException(message: String) : Exception(message)
class UnableToDeleteProjectException(message: String) : Exception(message)
class UnableToDeleteTaskException(message: String) : Exception(message)